const PAGINATION_OFFSET = 0;
const PAGINATION_OFFSET_MAX = 2147483600;

const PAGINATION_LIMIT = 5;
const PAGINATION_LIMIT_MAX = 100;

const PT_BR_WORD_REGEX = "^[#.0-9a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\\s]+$";

export {
  PAGINATION_OFFSET,
  PAGINATION_OFFSET_MAX,
  PAGINATION_LIMIT,
  PAGINATION_LIMIT_MAX,
  PT_BR_WORD_REGEX,
};
