name: ci-users-svc
on:
  pull_request:
    branches:
      - develop
jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM Modules
        run: yarn
      - name: Run unit tests
        run: yarn test

  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fireheet/users:dev
