name: ci-test-app
on:
  pull_request:
    branches:
      - develop
jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM Modules
        run: yarn
      - name: Run unit tests
        run: yarn test
